@startuml User Manage Reservation (PUT)

header Update Reservation Sequence Diagram
footer Page %page% of %lastpage%
title "User Manage Reservation (PUT)"

participant "User" as client
participant "<<javaScript>>\n:server" as server
participant "Middleware" as middleware
participant "<<router>>\n:reservations" as routerReservations
participant "<<controllers>>\n:reservations" as controllerReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationsDatabase

client->server ++:req.put('/reservations/:id')
server -> middleware ++:protect(req, res, next)\n, authorize('admin','user')
middleware --> server --:Returns user data
server->routerReservations ++:app.use("reservations", reservations)
routerReservations -> controllerReservations ++:updateReservation()
controllerReservations->modelReservation ++:findByIdAndUpdate({req.params.id, req.body})
modelReservation ->ReservationsDatabase ++: ReservationSchema
ReservationsDatabase --> modelReservation --: reservation
controllerReservations <-- modelReservation --:reservation
controllerReservations->client --:response
@enduml