@startuml User Register Sequence Diagram  
title User Register (POST)
actor User
participant "<<javaScript>>\n:Server" as Server
participant "<<controllers>>\n:Auth Controller" as Auth
participant "<<model>>\n:User" as Model
database "<<MongoDB>>\n:User" as Database


User -> Server: POST /api/v1/auth/register
activate Server

Server -> Auth: register(req, res, next)
activate Auth

Auth -> Model: create(req.body)
activate Model

Model -> Database ++: UserSchema
Database -> Model --: user data


Model --> Auth: Returns created user data
deactivate Model

Auth --> Server: sendTokenResponse(user, 200, res)
deactivate Auth

Server --> User: Response with token
deactivate Server
@enduml